CREATE SCHEMA IF NOT EXISTS dbo;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION dbo.get_date()
RETURNS TIMESTAMP
LANGUAGE sql
STABLE
AS $$
  SELECT CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata';
$$;
